trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
- group: sensitive-variables

steps:
# Build project
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'

# Mirror to Github
- task: mirror-git-repository-vsts-task@1
  inputs:
    sourceGitRepositoryUri: '$(Build.Repository.Uri)'
    sourceGitRepositoryPersonalAccessToken: '$(vsts.pat)'
    destinationGitRepositoryUri: 'https://github.com/bdimag/api-tools.git'
    destinationGitRepositoryPersonalAccessToken: '$(github.pat)'