trigger:
- master

pool:

  name: Azure Pipelines

variables:

  group: 'senstive-variables'

steps:

- task: swellaby.mirror-git-repository.mirror-git-repository-vsts-task.mirror-git-repository-vsts-task@1

  displayName: 'Mirror Git Repository to Github/api-tools'

  inputs:

    sourceGitRepositoryPersonalAccessToken: '$(vsts.pat)'

    destinationGitRepositoryUri: 'https://github.com/bdimag/api-tools.git'

    destinationGitRepositoryPersonalAccessToken: '$(github.pat)'
